### ISSUE TITLE
Too many Bugs please fix it and update it for latest devices 

### ISSUE THREAD

**Issue by imalixch** [typ-AhmedSleem/AnaMuslim#1]
I'm using android 10 and there are soo many bugs, please fix it.

**Comment by typ-AhmedSleem** [comment]
Fixed most of bugs but still working on Wizard issue.

Thanks bro

**Comment by typ-AhmedSleem** [comment]
Bugs are fixed now and app is ready to be used.

You can clone the repo and run it on your machine
